[profile.default]
src = "contracts"
test = "foundry/test"
out = "foundry/out"
libs = ["lib", "node_modules"]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200
evm_version = "paris"
remappings = [
  "@openzeppelin/=node_modules/@openzeppelin/"
]
